name: Build for Windows

on: 
  release:
    types:
      - created
      - published

jobs:
  build:
    name: Build for windows (.exe)
    runs-on: windows-latest
    steps:
      - name: Install UPX
        run: choco install upx -y
      - uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build exe with PyInstaller
        run: pyinstaller app.py --onefile --clean --exclude-module tensorflow
      - name: Upload .exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/app.exe
          asset_name: app.exe
          asset_content_type: application/vnd.microsoft.portable-executable
