name: Build for Linux

on: 
  release:
    types:
      - created

jobs:
  build:
    name: Build for linux 
    runs-on: ubuntu-latest
    steps:
      - name: Install UPX
        run: |
          sudo apt-get update -y
          sudo apt-get install -y upx
      - uses: actions/checkout@v2
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install and Create venv
        run: |
          pip install virtualenv
          python -m venv env
          source ./env/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build binary with PyInstaller
        run: pyinstaller app.py --onefile --clean
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/app
          asset_name: app
          asset_content_type: application/octet-stream
